# Generated by Django 2.0.6 on 2018-06-15 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edited'),
        ),
    ]
