# Generated by Django 2.0.6 on 2018-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180614_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
